### ISSUE TITLE
Setup only clickhouse backend

### ISSUE THREAD

**Issue by b17k0** [QuesmaOrg/quesma#984]
Hello! Is it possible to set up quesma without elasticsearch?
I mean, to have the following scheme: `Kibana -> Quesma -> ClickHouse`
With this configuration:
```yaml
#licenseKey: {your-quesma-license-key-if-needed} # license key is required for paid features such as `hydrolix` backend conector
frontendConnectors:
  - name: elastic-query
    type: elasticsearch-fe-query
    config:
      listenPort: 8080
backendConnectors:
  - name: my-clickhouse-data-source
    type: clickhouse-os
    config:
      url: "clickhouse://localhost:9000"
      adminUrl: "http://localhost:8123/play"
ingestStatistics: true
disableTelemetry: true
logging:
  path: "logs"
  level: "info"
  disableFileLogging: false
processors:
  - name: my-query-processor
    type: quesma-v1-processor-query
    config:
      indexes:
        some_transactions:
          target: [ my-clickhouse-data-source ]
          schemaOverrides:
            fields:
              timestamp:
                type: alias
                targetColumnName: "started_at"
              id:
                type: "keyword"
              started_at:
                type: "date"
              uuid:
                type: "keyword"
              account_id:
                type: "keyword"
              state:
                type: "keyword"
              category:
                type: "keyword"
              balance_at_start:
                type: "float"
              balance_at_end:
                type: "float"
              finished_at:
                type: "date"
              currency_id:
                type: "keyword"
              merchant_id:
                type: "keyword"
              user_login:
                type: "keyword"
              # more fields
        "*":       # DO NOT remove, always required
          target: [ my-clickhouse-data-source ]
pipelines:
  - name: my-pipeline-elasticsearch-query-clickhouse
    frontendConnectors: [ elastic-query ]
    processors: [ my-query-processor ]
    backendConnectors: [ my-clickhouse-data-source ]

```
I get the following error:

```
2024/11/13 15:51:54 Config validation failed: 2 errors occurred:
	* pipeline my-pipeline-elasticsearch-query-clickhouse has a processor of type quesma-v1-processor-query which requires having one elasticsearch backend connector
	* query processor requires two backend connectors
```
